### ISSUE TITLE
[F18] Uppdatering patientjournal

### ISSUE THREAD

**Issue by SofieHellstrom** [SofieHellstrom/ProjectHospital#17]
Som läkare vill jag kunna uppdatera patientjournalen för att hålla redo på patientens status.

Acceptanskriteria/tasks:

- Patientjournal måste finnas
- Anteckningar i patientjournalen ska kunna läggas till
- Anteckningar i patientjournalen ska kunna ändras
- Anteckningar i patientjournalen ska kunna tas bort av läkaren som skrivit dem inom ett viss tidsram
- Felmeddelande skall visas om anteckningen inte kan tas bort
- Uppdateringar ska sparas i databasen
- Uppdateringar skall vara synliga så fort de har sparats
- Felmeddelande skall visas om uppdateringen inte kan sparas
- Datumstämpla bör visas i varje sparat uppdatering
- Datumstämpla bör visas i varje sparat uppdateringsändring

**Comment by Mirrorspawn** [comment]
Kvar att göra: 

- Ändring av anteckningar (skall man kunna göra detta? Vilka anteckningar i sådana fall?)
- Borttagning av anteckning.
- Felmeddelande om anteckning inte kan sparas.
