### ISSUE TITLE
[F07] Patientregistrering

### ISSUE THREAD

**Issue by SofieHellstrom** [SofieHellstrom/ProjectHospital#2]
Som receptionist vill jag kunna registrera patienter i systemet så att deras information blir tillgänglig för relevanta användare och processer.

Acceptanskriteria/tasks:
- GUI-Registreringsform med patientens personnummer, namn, adress, tid av registrering, ...
- Varning för obligatoriska fält som måste fyllas i innan registreringen kan sparas
- Registreringen måste sparas i databasen
- Bekräftelsemeddelande när registreringen har sparats

**Comment by SofieHellstrom** [comment]
Ska man ha möjlighet till redigering av registreringen? (behövs en task till då)

**Comment by Mirrorspawn** [comment]
Tror vi pratat om denna redan, men när man väl har sparat en patient så hamnar ju uppgifterna i databasen. 
Så att redigera en registrering och att redigera en patient blir samma sak. Tror vi har redigera patient också väl.
