### ISSUE TITLE
[F23] Patientreferens från en läkare till en annan

### ISSUE THREAD

**Issue by SofieHellstrom** [SofieHellstrom/ProjectHospital#21]
Som läkare vill jag kunna referera mina patienter till en annan läkare för att en annan läkares specialitet är mer lämplig än min i diagnosställningen.

Acceptanskriteria/tasks:

- Aktiv patientjournal måste finnas
- Sökfunktion GUI med möjlighet att söka på läkare-namn och -specialitet måste finnas
- Sökresultat GUI måste finnas med möjlighet att sortera på namn och specialitet
- Möjlighet att referera patient till läkare via sökresultat GUI måste finnas
- Vid lyckad referens måste bekräftelsemeddelande visas
- Automatisk anteckning i patientjournalen måste skapas vid lyckad referens
- Läkaren som patienten refererades till ska få meddelande om referensen
- Refererade läkaren måste skapa patientbesök #13 , #14, #15    i sitt schema
- Besökstiden ska sparas i patientjournalen
- Kallelse måste skickas till patienten

**Comment by Mirrorspawn** [comment]
Skall vi ha med en meddelande-funktion?
Ny userstory för att kunna se referrals?
Troligare att läkaren som blir refererad till (eller den avdelningens receptionist) bestämmer tid för besök.
