### ISSUE TITLE
[F08] Skapa patientjournal

### ISSUE THREAD

**Issue by SofieHellstrom** [SofieHellstrom/ProjectHospital#9]
Som receptionist vill jag kunna skapa en patientjournal när jag har färdigregistrerat patienten, för att hens information skall finnas tillgänglig för både beroende personal och patienten själv.

Acceptanskriteria/tasks:
- En GUI-patientjournalform ska finnas tillgänglig efter patienten har registrerats
- Om patienten redan har ett befintlig patientjournal skall denna visas istället
- Rätt information skall kunna fyllas i: anledning till skapandet av journalen, valt läkare, annan lämplig information
- Varning för obligatoriska fält som måste fyllas i innan patientjournalen kan sparas
- Patientjournalen måste sparas i databasen
- Bekräftelsemeddelande när patientjournalen har sparats
- Möjligheten att omredigera information vid behov inom viss tidsram

**Comment by Mirrorspawn** [comment]
Viss omdesign av funktionaliteten, men patientjournal "skapas"
